In [1]:
import pandas as pd

# Student basic info
students = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4, 5],
    "Name": ["Dipam", "Raj", "Anita", "Karan", "Meena"],
    "Age": [28, 26, 27, 24, 26]
})

# Marks table
marks = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4, 5],
    "Marks": [90, 85, 87, 70, 95]
})

In [7]:
# This joins tables using common column.
df = pd.merge(students, marks, on="Student_ID")
print(df)

#✅ Inner Join (default) Only matching rows.

pd.merge(students, marks, on="Student_ID", how="inner")

#✅ Left Join All rows from left table, matching from right.
pd.merge(students, marks, on="Student_ID", how="left")
#✅ Right Join All rows from right table, matching from left.
pd.merge(students, marks, on="Student_ID", how="right")
#✅ Outer Join All rows from both tables, NaN for non-matching.
pd.merge(students, marks, on="Student_ID", how="outer")

   Student_ID   Name  Age  Marks
0           1  Dipam   28     90
1           2    Raj   26     85
2           3  Anita   27     87
3           4  Karan   24     70
4           5  Meena   26     95

   Student_ID   Name  Age  Marks
0           1  Dipam   28     90
1           2    Raj   26     85
2           3  Anita   27     87
3           4  Karan   24     70
4           5  Meena   26     95

In [9]:
marks = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4],
    "Marks": [90, 85, 87, 70]
})

df = pd.merge(students, marks, on="Student_ID", how="left")
print(df)

   Student_ID   Name  Age  Marks
0           1  Dipam   28   90.0
1           2    Raj   26   85.0
2           3  Anita   27   87.0
3           4  Karan   24   70.0
4           5  Meena   26    NaN

In [11]:
#3️⃣ Concatenation (Stacking)

#Instead of joining by column, you can stack rows.

df1 = students.iloc[:3]
print(df1)
df2 = students.iloc[3:]

pd.concat([df1, df2])

   Student_ID   Name  Age
0           1  Dipam   28
1           2    Raj   26
2           3  Anita   27

   Student_ID   Name  Age
0           1  Dipam   28
1           2    Raj   26
2           3  Anita   27
3           4  Karan   24
4           5  Meena   26

In [ ]:
#Assignment
#1️⃣ Create new DataFrame called fees:
#Student_ID: [1,2,3,4]
#Fees_Paid: [True, True, False, True]
#2️⃣ Merge students + marks + fees using left join
#3️⃣ Show students who have NOT paid fees

Fees = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4],
    "Fees_Paid": [True, True, False, True]
})

df = pd.merge(students, marks, on="Student_ID", how="left")
df = pd.merge(df, Fees, on="Student_ID", how="left")

print(df)

# Show students who have NOT paid fees
df[df["Fees_Paid"] == False].reset_index(drop=True)

   Student_ID   Name  Age  Marks Fees_Paid
0           1  Dipam   28   90.0      True
1           2    Raj   26   85.0      True
2           3  Anita   27   87.0     False
3           4  Karan   24   70.0      True
4           5  Meena   26    NaN       NaN

C:\Users\Dipam\AppData\Local\Temp\ipykernel_14880\1265146884.py:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Fees_Paid"] = df["Fees_Paid"].fillna(False)